### ISSUE TITLE
Compile error with Intel 2019

### ISSUE THREAD

**Issue by mkrompiec** [dftd4/dftd4#47]
Same error as https://github.com/grimme-lab/xtb/issues/107, when compiling with icc (ICC) 19.1.0.166 20191121:

[39/65] Compiling Fortran object 'dftd4@sta/source_dftd4.f90.o'.
FAILED: dftd4@sta/source_dftd4.f90.o
ifort -Idftd4@sta -I. -I.. -I../include -D_FILE_OFFSET_BITS=64 -warn general -warn truncated_source -g -axAVX -traceback -stand f08 -check bounds -qopenmp -fPIC -module dftd4@sta   -o 'dftd4@sta/source_dftd4.f90.o' -c ../source/dftd4.f90
../source/dftd4.f90(1239): error #6752: Since the OpenMP* DEFAULT(NONE) clause applies, the PRIVATE, SHARED, REDUCTION, FIRSTPRIVATE, or LASTPRIVATE attribute must be explicitly specified for every variable.   [TX]
      do concurrent(tx = -rep(1):rep(1), &
--------------------^
../source/dftd4.f90(1240): error #6752: Since the OpenMP* DEFAULT(NONE) clause applies, the PRIVATE, SHARED, REDUCTION, FIRSTPRIVATE, or LASTPRIVATE attribute must be explicitly specified for every variable.   [TY]
            &       ty = -rep(2):rep(2), &
--------------------^
../source/dftd4.f90(1241): error #6752: Since the OpenMP* DEFAULT(NONE) clause applies, the PRIVATE, SHARED, REDUCTION, FIRSTPRIVATE, or LASTPRIVATE attribute must be explicitly specified for every variable.   [TZ]
            &       tz = -rep(3):rep(3))
--------------------^
../source/dftd4.f90(1270): error #6752: Since the OpenMP* DEFAULT(NONE) clause applies, the PRIVATE, SHARED, REDUCTION, FIRSTPRIVATE, or LASTPRIVATE attribute must be explicitly specified for every variable.   [TX]
         do concurrent(tx = -rep(1):rep(1), &
-----------------------^
../source/dftd4.f90(1271): error #6752: Since the OpenMP* DEFAULT(NONE) clause applies, the PRIVATE, SHARED, REDUCTION, FIRSTPRIVATE, or LASTPRIVATE attribute must be explicitly specified for every variable.   [TY]
               &       ty = -rep(2):rep(2), &
-----------------------^
../source/dftd4.f90(1272): error #6752: Since the OpenMP* DEFAULT(NONE) clause applies, the PRIVATE, SHARED, REDUCTION, FIRSTPRIVATE, or LASTPRIVATE attribute must be explicitly specified for every variable.   [TZ]
               &       tz = -rep(3):rep(3))
-----------------------^
compilation aborted for ../source/dftd4.f90 (code 1)

**Comment by awvwgk** [comment]
Unfortunately, this is an issue with the latest Intel compiler, the concurrent iteration counters are correctly declared as private, but this clause is simply ignored by the Intel compiler. To fix it the offending code pieces must be rewritten entirely.

**Comment by mkrompiec** [comment]
This will pop up more often as more people will move to Intel 2019... Would it make sense to report this to Intel as a bug? 
If you can copy that part from xtb, then perhaps this is the easiest way to fix this.

**Comment by awvwgk** [comment]
The usual `sed -i 's/(none)/(shared)/g' source/dftd4.f90` can be used as workaround or to generate the necessary patches.

**Comment by awvwgk** [comment]
> This will pop up more often as more people will move to Intel 2019... Would it make sense to report this to Intel as a bug?

Actually, this is an Intel 2020 issue, it works fine with Intel 2019, but they bumped the version from 19.0 to 19.1 for the 2020 release for whatever reason.

This construct is working with 19.0.3.199 20190206 and is failing with 19.1.1.217 20200306: `ifort -qopenmp mwe.f90`

```fortran
implicit none
integer :: i, j
integer :: vec(10)

vec(:) = 0
!$omp parallel do default(none) reduction(+:vec) private(i, j)
do i = 1, size(vec)
   do concurrent(j = 1:size(vec))
      vec(i) = vec(i) + j * j
   end do
end do
end
```

Dropping the concurrency to workaround the issue is straight-forward if not tedious.

**Comment by mkrompiec** [comment]
Seems like this change is mentioned in Intel's changelog: https://software.intel.com/content/www/us/en/develop/articles/intel-fortran-compiler-191-for-linux-release-notes-for-intel-parallel-studio-xe-2020.html#changed_comp_behaviour
