### ISSUE TITLE
Building with openMP (GCC 9)

### ISSUE THREAD

**Issue by mkrompiec** [dftd4/dftd4#13]
I'm trying to build with GCC 9.1.0, Intel MKL & LAPACK. At the linking stage, it can't find GOMP (even though the library is in the path):
```
[63/65] Linking target dftd4_c.
FAILED: dftd4_c
cc  -o dftd4_c 'dftd4_c@exe/tests_c_api_example.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group libdftd4.so.2.3.1 -lpthread -lm -ldl -pthread '-Wl,-rpath,$ORIGIN/' -Wl,-rpath-link,/home/m212767/dftd4/dftd4-master/build/ -lgfortran -Wl,--end-group
libdftd4.so.2.3.1: undefined reference to `GOMP_loop_maybe_nonmonotonic_runtime_next@GOMP_5.0'
libdftd4.so.2.3.1: undefined reference to `GOMP_parallel_loop_maybe_nonmonotonic_runtime@GOMP_5.0'
collect2: error: ld returned 1 exit status
[64/65] Linking target dftd4_cpp.
FAILED: dftd4_cpp
c++  -o dftd4_cpp 'dftd4_cpp@exe/tests_cpp_api_example.cpp.o' -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group libdftd4.so.2.3.1 -lpthread -lm -ldl -pthread '-Wl,-rpath,$ORIGIN/' -Wl,-rpath-link,/home/m212767/dftd4/dftd4-master/build/ -lgfortran -Wl,--end-group
libdftd4.so.2.3.1: undefined reference to `GOMP_loop_maybe_nonmonotonic_runtime_next@GOMP_5.0'
libdftd4.so.2.3.1: undefined reference to `GOMP_parallel_loop_maybe_nonmonotonic_runtime@GOMP_5.0'
collect2: error: ld returned 1 exit status
[65/65] Linking target d4test.
ninja: build stopped: subcommand failed.
```
How can this be solved?
Thanks,
Michal

**Comment by awvwgk** [comment]
I think it is missing the openmp library in the linkline. I will check this.

**Comment by awvwgk** [comment]
I can confirm that `dftd4` fails when compiled with GCC v9.1.0 and MKL v19.0.3, but it works fine together with LAPACK/BLAS and openBLAS. Also with OpenMP disabled everything runs fine.

**Comment by mkrompiec** [comment]
In the end, this was the "winning" sequence, with GCC 8 and free Intel redistributable libraries (so Intel Parallel Studio is not actually required!):

module load gcc-8.3.0
export FC=gfortran
export CC=gcc
source /path/intel/ifort_redist/bin/compilervars.sh intel64
source /path/MKL/bin/compilervars.sh -arch intel64  -platform linux
meson setup build
ninja -C build
